# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppUI.ui'
#
# Created: Tue Dec 17 23:13:58 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(600, 500)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_samples = QtGui.QWidget()
        self.tab_samples.setObjectName(_fromUtf8("tab_samples"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_samples)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graph = myCurveWidget(self.tab_samples)
        self.graph.setObjectName(_fromUtf8("graph"))
        self.verticalLayout_3.addWidget(self.graph)
        self.hslider = QtGui.QSlider(self.tab_samples)
        self.hslider.setMaximum(0)
        self.hslider.setOrientation(QtCore.Qt.Horizontal)
        self.hslider.setInvertedAppearance(False)
        self.hslider.setInvertedControls(False)
        self.hslider.setTickPosition(QtGui.QSlider.NoTicks)
        self.hslider.setObjectName(_fromUtf8("hslider"))
        self.verticalLayout_3.addWidget(self.hslider)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btn_get = QtGui.QPushButton(self.tab_samples)
        self.btn_get.setCheckable(True)
        self.btn_get.setAutoDefault(False)
        self.btn_get.setDefault(False)
        self.btn_get.setFlat(False)
        self.btn_get.setObjectName(_fromUtf8("btn_get"))
        self.verticalLayout_2.addWidget(self.btn_get)
        self.btn_save = QtGui.QPushButton(self.tab_samples)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.verticalLayout_2.addWidget(self.btn_save)
        self.btn_load = QtGui.QPushButton(self.tab_samples)
        self.btn_load.setEnabled(False)
        self.btn_load.setObjectName(_fromUtf8("btn_load"))
        self.verticalLayout_2.addWidget(self.btn_load)
        self.spinBox = QtGui.QSpinBox(self.tab_samples)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setWrapping(True)
        self.spinBox.setMaximum(0)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_2.addWidget(self.spinBox)
        self.line = QtGui.QFrame(self.tab_samples)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.chk_pump = QtGui.QCheckBox(self.tab_samples)
        self.chk_pump.setChecked(True)
        self.chk_pump.setObjectName(_fromUtf8("chk_pump"))
        self.verticalLayout_2.addWidget(self.chk_pump)
        self.chk_drum = QtGui.QCheckBox(self.tab_samples)
        self.chk_drum.setChecked(True)
        self.chk_drum.setObjectName(_fromUtf8("chk_drum"))
        self.verticalLayout_2.addWidget(self.chk_drum)
        self.chk_temp = QtGui.QCheckBox(self.tab_samples)
        self.chk_temp.setChecked(True)
        self.chk_temp.setObjectName(_fromUtf8("chk_temp"))
        self.verticalLayout_2.addWidget(self.chk_temp)
        self.chk_pres = QtGui.QCheckBox(self.tab_samples)
        self.chk_pres.setChecked(True)
        self.chk_pres.setObjectName(_fromUtf8("chk_pres"))
        self.verticalLayout_2.addWidget(self.chk_pres)
        self.verticalLayout_2.setStretch(8, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_samples, _fromUtf8(""))
        self.tab_conf = QtGui.QWidget()
        self.tab_conf.setObjectName(_fromUtf8("tab_conf"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_conf)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_up = QtGui.QPushButton(self.tab_conf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_up.sizePolicy().hasHeightForWidth())
        self.btn_up.setSizePolicy(sizePolicy)
        self.btn_up.setObjectName(_fromUtf8("btn_up"))
        self.horizontalLayout_2.addWidget(self.btn_up)
        self.btn_down = QtGui.QPushButton(self.tab_conf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_down.sizePolicy().hasHeightForWidth())
        self.btn_down.setSizePolicy(sizePolicy)
        self.btn_down.setObjectName(_fromUtf8("btn_down"))
        self.horizontalLayout_2.addWidget(self.btn_down)
        self.btn_set = QtGui.QPushButton(self.tab_conf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_set.sizePolicy().hasHeightForWidth())
        self.btn_set.setSizePolicy(sizePolicy)
        self.btn_set.setObjectName(_fromUtf8("btn_set"))
        self.horizontalLayout_2.addWidget(self.btn_set)
        self.btn_sync = QtGui.QPushButton(self.tab_conf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sync.sizePolicy().hasHeightForWidth())
        self.btn_sync.setSizePolicy(sizePolicy)
        self.btn_sync.setObjectName(_fromUtf8("btn_sync"))
        self.horizontalLayout_2.addWidget(self.btn_sync)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_description = QtGui.QLabel(self.tab_conf)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_description.setFont(font)
        self.label_description.setObjectName(_fromUtf8("label_description"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_description)
        self.lbl_descr = QtGui.QLabel(self.tab_conf)
        self.lbl_descr.setObjectName(_fromUtf8("lbl_descr"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbl_descr)
        self.label_value = QtGui.QLabel(self.tab_conf)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_value.setFont(font)
        self.label_value.setObjectName(_fromUtf8("label_value"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_value)
        self.spnbox_param = QtGui.QSpinBox(self.tab_conf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnbox_param.sizePolicy().hasHeightForWidth())
        self.spnbox_param.setSizePolicy(sizePolicy)
        self.spnbox_param.setMaximum(0)
        self.spnbox_param.setObjectName(_fromUtf8("spnbox_param"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spnbox_param)
        self.label_limits = QtGui.QLabel(self.tab_conf)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_limits.setFont(font)
        self.label_limits.setObjectName(_fromUtf8("label_limits"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_limits)
        self.lbl_lim = QtGui.QLabel(self.tab_conf)
        self.lbl_lim.setObjectName(_fromUtf8("lbl_lim"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lbl_lim)
        self.label_step = QtGui.QLabel(self.tab_conf)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step.sizePolicy().hasHeightForWidth())
        self.label_step.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_step.setFont(font)
        self.label_step.setObjectName(_fromUtf8("label_step"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_step)
        self.lbl_step = QtGui.QLabel(self.tab_conf)
        self.lbl_step.setObjectName(_fromUtf8("lbl_step"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lbl_step)
        self.label = QtGui.QLabel(self.tab_conf)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label)
        self.lst_params = QtGui.QListWidget(self.tab_conf)
        self.lst_params.setObjectName(_fromUtf8("lst_params"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lst_params)
        self.label_raw = QtGui.QLabel(self.tab_conf)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_raw.setFont(font)
        self.label_raw.setObjectName(_fromUtf8("label_raw"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_raw)
        self.label_3 = QtGui.QLabel(self.tab_conf)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_3)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_conf, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBox_COMport = QtGui.QSpinBox(self.tab)
        self.spinBox_COMport.setProperty("value", 16)
        self.spinBox_COMport.setObjectName(_fromUtf8("spinBox_COMport"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_COMport)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.txt_status = QtGui.QPlainTextEdit(self.centralwidget)
        self.txt_status.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.txt_status.sizePolicy().hasHeightForWidth())
        self.txt_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.txt_status.setFont(font)
        self.txt_status.setObjectName(_fromUtf8("txt_status"))
        self.verticalLayout.addWidget(self.txt_status)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Winsch-PC", None))
        self.btn_get.setText(_translate("MainWindow", "get", None))
        self.btn_save.setText(_translate("MainWindow", "save", None))
        self.btn_load.setText(_translate("MainWindow", "load", None))
        self.chk_pump.setText(_translate("MainWindow", "Pump rpm", None))
        self.chk_drum.setText(_translate("MainWindow", "Drum rpm", None))
        self.chk_temp.setText(_translate("MainWindow", "Temperature", None))
        self.chk_pres.setText(_translate("MainWindow", "Pressure", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_samples), _translate("MainWindow", "Loggning", None))
        self.btn_up.setText(_translate("MainWindow", "up", None))
        self.btn_down.setText(_translate("MainWindow", "down", None))
        self.btn_set.setText(_translate("MainWindow", "set", None))
        self.btn_sync.setText(_translate("MainWindow", "sync", None))
        self.label_description.setText(_translate("MainWindow", "Description", None))
        self.lbl_descr.setText(_translate("MainWindow", "TextLabel", None))
        self.label_value.setText(_translate("MainWindow", "Value", None))
        self.label_limits.setText(_translate("MainWindow", "Limits", None))
        self.lbl_lim.setText(_translate("MainWindow", "TextLabel", None))
        self.label_step.setText(_translate("MainWindow", "Step", None))
        self.lbl_step.setText(_translate("MainWindow", "TextLabel", None))
        self.label.setText(_translate("MainWindow", "Parameters", None))
        self.label_raw.setText(_translate("MainWindow", "Raw value", None))
        self.label_3.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conf), _translate("MainWindow", "Paramterar", None))
        self.label_2.setText(_translate("MainWindow", "COM port", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Inställningar", None))

from guiqwtWidget import myCurveWidget
