# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppUI.ui'
#
# Created: Wed Sep  3 22:40:10 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(600, 577)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_samples = QtGui.QWidget()
        self.tab_samples.setEnabled(False)
        self.tab_samples.setObjectName(_fromUtf8("tab_samples"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_samples)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graph = TimePlot(self.tab_samples)
        self.graph.setObjectName(_fromUtf8("graph"))
        self.verticalLayout_3.addWidget(self.graph)
        self.hslider = QtGui.QSlider(self.tab_samples)
        self.hslider.setMaximum(0)
        self.hslider.setOrientation(QtCore.Qt.Horizontal)
        self.hslider.setInvertedAppearance(False)
        self.hslider.setInvertedControls(False)
        self.hslider.setTickPosition(QtGui.QSlider.NoTicks)
        self.hslider.setObjectName(_fromUtf8("hslider"))
        self.verticalLayout_3.addWidget(self.hslider)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btn_get = QtGui.QPushButton(self.tab_samples)
        self.btn_get.setCheckable(True)
        self.btn_get.setAutoDefault(False)
        self.btn_get.setDefault(False)
        self.btn_get.setFlat(False)
        self.btn_get.setObjectName(_fromUtf8("btn_get"))
        self.verticalLayout_2.addWidget(self.btn_get)
        self.btn_save = QtGui.QPushButton(self.tab_samples)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.verticalLayout_2.addWidget(self.btn_save)
        self.btn_load = QtGui.QPushButton(self.tab_samples)
        self.btn_load.setEnabled(False)
        self.btn_load.setObjectName(_fromUtf8("btn_load"))
        self.verticalLayout_2.addWidget(self.btn_load)
        self.spinBox = QtGui.QSpinBox(self.tab_samples)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setWrapping(True)
        self.spinBox.setMaximum(0)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_2.addWidget(self.spinBox)
        self.line = QtGui.QFrame(self.tab_samples)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.chk_pump = QtGui.QCheckBox(self.tab_samples)
        self.chk_pump.setChecked(True)
        self.chk_pump.setObjectName(_fromUtf8("chk_pump"))
        self.verticalLayout_2.addWidget(self.chk_pump)
        self.chk_drum = QtGui.QCheckBox(self.tab_samples)
        self.chk_drum.setChecked(True)
        self.chk_drum.setObjectName(_fromUtf8("chk_drum"))
        self.verticalLayout_2.addWidget(self.chk_drum)
        self.chk_temp = QtGui.QCheckBox(self.tab_samples)
        self.chk_temp.setChecked(True)
        self.chk_temp.setObjectName(_fromUtf8("chk_temp"))
        self.verticalLayout_2.addWidget(self.chk_temp)
        self.chk_pres = QtGui.QCheckBox(self.tab_samples)
        self.chk_pres.setChecked(True)
        self.chk_pres.setObjectName(_fromUtf8("chk_pres"))
        self.verticalLayout_2.addWidget(self.chk_pres)
        self.verticalLayout_2.setStretch(8, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_samples, _fromUtf8(""))
        self.tab_params = QtGui.QWidget()
        self.tab_params.setEnabled(False)
        self.tab_params.setObjectName(_fromUtf8("tab_params"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_params)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_up = QtGui.QPushButton(self.tab_params)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_up.sizePolicy().hasHeightForWidth())
        self.btn_up.setSizePolicy(sizePolicy)
        self.btn_up.setObjectName(_fromUtf8("btn_up"))
        self.horizontalLayout_2.addWidget(self.btn_up)
        self.btn_down = QtGui.QPushButton(self.tab_params)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_down.sizePolicy().hasHeightForWidth())
        self.btn_down.setSizePolicy(sizePolicy)
        self.btn_down.setObjectName(_fromUtf8("btn_down"))
        self.horizontalLayout_2.addWidget(self.btn_down)
        self.btn_select = QtGui.QPushButton(self.tab_params)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select.sizePolicy().hasHeightForWidth())
        self.btn_select.setSizePolicy(sizePolicy)
        self.btn_select.setObjectName(_fromUtf8("btn_select"))
        self.horizontalLayout_2.addWidget(self.btn_select)
        self.btn_sync = QtGui.QPushButton(self.tab_params)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sync.sizePolicy().hasHeightForWidth())
        self.btn_sync.setSizePolicy(sizePolicy)
        self.btn_sync.setObjectName(_fromUtf8("btn_sync"))
        self.horizontalLayout_2.addWidget(self.btn_sync)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab_params)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.tbl_params = QtGui.QTableView(self.tab_params)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tbl_params.sizePolicy().hasHeightForWidth())
        self.tbl_params.setSizePolicy(sizePolicy)
        self.tbl_params.setWordWrap(False)
        self.tbl_params.setObjectName(_fromUtf8("tbl_params"))
        self.tbl_params.horizontalHeader().setDefaultSectionSize(80)
        self.tbl_params.horizontalHeader().setStretchLastSection(True)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.tbl_params)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_params, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_settings)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab_settings)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBox_COMport = QtGui.QSpinBox(self.tab_settings)
        self.spinBox_COMport.setProperty("value", 16)
        self.spinBox_COMport.setObjectName(_fromUtf8("spinBox_COMport"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_COMport)
        self.label_4 = QtGui.QLabel(self.tab_settings)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_btmac = QtGui.QLineEdit(self.tab_settings)
        self.lineEdit_btmac.setObjectName(_fromUtf8("lineEdit_btmac"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_btmac)
        self.btn_connect = QtGui.QPushButton(self.tab_settings)
        self.btn_connect.setObjectName(_fromUtf8("btn_connect"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.btn_connect)
        self.tabWidget.addTab(self.tab_settings, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.txt_status = QtGui.QPlainTextEdit(self.centralwidget)
        self.txt_status.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.txt_status.sizePolicy().hasHeightForWidth())
        self.txt_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.txt_status.setFont(font)
        self.txt_status.setObjectName(_fromUtf8("txt_status"))
        self.verticalLayout.addWidget(self.txt_status)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Winsch-PC", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_get.setText(QtGui.QApplication.translate("MainWindow", "Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_load.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_pump.setText(QtGui.QApplication.translate("MainWindow", "Pump rpm", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_drum.setText(QtGui.QApplication.translate("MainWindow", "Drum rpm", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_temp.setText(QtGui.QApplication.translate("MainWindow", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_pres.setText(QtGui.QApplication.translate("MainWindow", "Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_samples), QtGui.QApplication.translate("MainWindow", "Loggning", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_up.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_down.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_select.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sync.setText(QtGui.QApplication.translate("MainWindow", "Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_params), QtGui.QApplication.translate("MainWindow", "Paramterar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "COM port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Bluetooth MAC-address", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_btmac.setText(QtGui.QApplication.translate("MainWindow", "00:06:66:43:11:8D", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_connect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), QtGui.QApplication.translate("MainWindow", "Inställningar", None, QtGui.QApplication.UnicodeUTF8))

from TimePlot import TimePlot
